apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "etcd-manager.backend.fullname" . | quote }}
  labels:
    {{- include "etcd-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "etcd-manager.backendSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "etcd-manager.backendSelectorLabels" . | nindent 8 }}
        {{- with .Values.backend.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.backend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "etcd-manager.serviceAccountName" . | quote }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      {{- with .Values.backend.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: backend
          image: {{ include "etcd-manager.image" (dict "ctx" . "image" .Values.backend.image) | quote }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          {{- with .Values.backend.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: CONFIG_PATH
              value: /app/configs/config.yaml
            {{- range $k, $v := .Values.backend.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          {{- with .Values.backend.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /app/configs/config.yaml
              subPath: config.yaml
              readOnly: true
            {{- if .Values.backend.persistence.enabled }}
            - name: data
              mountPath: /app/data
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.backend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.backend.readinessProbe | nindent 12 }}
          {{- with .Values.backend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "etcd-manager.backend.fullname" . | quote }}
        {{- if .Values.backend.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ default (include "etcd-manager.backend.fullname" .) .Values.backend.persistence.existingClaim | quote }}
        {{- end }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
